In [1]:
import numpy as np

In [34]:
a = np.zeros(10)
b = np.ones(10)

In [32]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
a+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [43]:
d = np.arange(10,51)

In [44]:
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [41]:
e = np.arange(10,51,2)

In [42]:
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [45]:
f = np.arange(0,9)

In [48]:
g = f.reshape([3,3])

In [49]:
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])